#!/bin/bash

apt-get update -y
apt-get upgrade -y

apt-get install -y curl vim git

mkdir /home/ubuntu/test_dir
echo "Fisier test" > /home/ubuntu/test_dir/test_file.txt

chmod -R 755 /home/ubuntu/test_dir

echo "Scriptul a fost executat cu succes!" > /home/ubuntu/test_dir/log.txt
