name: Terraform apply

run-name: ${{ github.actor }} is deploying on AWS 🚀
on: [push]
jobs:
  Deploy-AWS-Ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_MELANIA }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_MELANIA }}
          aws-region: eu-west-1
      - name: Checkout Repository
        uses: actions/checkout@v4
      - run: ls -lah   
      - name: Deploy Infrastructure
        run: |
          terraform init
      - run: |
          terraform apply -auto-approve
